version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    ports:
      - 8085:8080
      - 50001:50000
    volumes:
      - ./data:/var/jenkins_home
    # restart: always
    networks:
      - net_jenkins

volumes:
  jenkins_home:

networks:
  net_jenkins:
