# docker compose de redis
version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    # restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: redis-server --loglevel warning --requirepass "Password123"
    
